# Generated by Django 5.0.1 on 2024-02-22 19:21

import image_loader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=image_loader.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
