# Generated by Django 5.0.1 on 2024-03-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_loader', '0004_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=50),
        ),
    ]
