# Generated by Django 5.0.1 on 2024-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_loader', '0005_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.AddField(
            model_name='message',
            name='code',
            field=models.CharField(default='', max_length=8),
        ),
    ]
